# Generated by Django 3.2.4 on 2021-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_profile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
