# Generated by Django 3.2.4 on 2021-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210620_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
