# Generated by Django 3.2.4 on 2021-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_profile_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
